name: jinbeanpod_83904710
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  supabase_flutter: ^2.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/jinbean_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dependency_overrides:
  jinbeanpod_83904710_f2f:
    path: ./local_packages/jinbeanpod_f2f
