name: jinbeanpod_83904710
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^7.0.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3
  supabase_flutter: ^2.3.4
  intl: ^0.20.2
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/jinbean_marker-0.png
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png
    - assets/images/jinbean_logo.png
    - assets/images/jinbean_logo-1.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/jinbean_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dependency_overrides:
  jinbeanpod_83904710_f2f:
    path: ./local_packages/jinbeanpod_f2f
