-- =====================================================
-- 基于真实表结构的准确Provider测试数据
-- 适用于真实的 provider_profiles 表结构
-- 创建日期: 2025-01-08
-- =====================================================

-- 确保必要的扩展已启用
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 插入测试Provider数据，符合真实表结构
INSERT INTO public.provider_profiles (
    id,
    user_id,
    business_address,
    service_areas,
    service_categories,
    status,
    documents,
    license_number,
    review_count,
    provider_type,
    has_gst_hst,
    bn_number,
    annual_income_estimate,
    tax_status_notice_shown,
    tax_report_available,
    address_id,
    certification_files,
    certification_status,
    is_certified,
    experience_years,
    service_radius_km,
    base_price,
    pricing_type,
    work_schedule,
    team_members,
    payment_methods,
    is_active,
    vacation_mode,
    notification_settings,
    display_name,
    bio,
    avatar_url,
    phone,
    email,
    rating,
    tags,
    social_links,
    custom_fields,
    created_at,
    updated_at
) VALUES
-- 樱花日料 - 日式料理专家
(
    'test_provider_001',
    'test_user_001',
    '123 Sakura Street, Vancouver, BC V6B 1A1',
    ARRAY['V6B', 'V6Z', 'V5K'],
    ARRAY['1010000', '1010100', '1010200'],
    'active',
    ARRAY['license_001.pdf', 'health_permit_001.pdf'],
    'BC-REST-001',
    156,
    'individual',
    true,
    'BN123456789RT0001',
    85000,
    true,
    false,
    NULL,
    '{"business_license": "valid", "health_permit": "valid", "food_safety": "certified"}',
    'verified',
    true,
    8,
    15.0,
    120.00,
    'fixed_price',
    '{"monday": {"open": "11:00", "close": "22:00"}, "tuesday": {"open": "11:00", "close": "22:00"}, "wednesday": {"open": "11:00", "close": "22:00"}, "thursday": {"open": "11:00", "close": "22:00"}, "friday": {"open": "11:00", "close": "23:00"}, "saturday": {"open": "11:00", "close": "23:00"}, "sunday": {"open": "12:00", "close": "21:00"}}',
    '{"head_chef": "Tanaka-san", "sous_chef": "Sato-san", "servers": 3}',
    '{"cash": true, "credit_card": true, "debit": true, "mobile_payment": true}',
    true,
    false,
    '{"email": true, "sms": true, "push": true}',
    '{"en": "Sakura Japanese Cuisine", "zh": "樱花日料", "fr": "Cuisine Japonaise Sakura"}',
    '{"en": "Authentic Japanese cuisine with traditional recipes and modern presentation", "zh": "正宗日式料理，传统配方现代呈现", "fr": "Cuisine japonaise authentique avec des recettes traditionnelles et une présentation moderne"}',
    'https://example.com/avatars/sakura_restaurant.jpg',
    '+1-604-555-0001',
    'info@sakurarestaurant.com',
    4.8,
    ARRAY['日式料理', '寿司', '刺身', '拉面', '天妇罗', '正宗', '新鲜'],
    '{"instagram": "@sakura_vancouver", "facebook": "SakuraRestaurantVancouver", "website": "https://sakurarestaurant.com"}',
    '{"specialty": "sushi_sashimi", "chef_origin": "Tokyo", "established": "2016"}',
    NOW(),
    NOW()
),

-- 金龙餐厅 - 中式料理专家
(
    'test_provider_002',
    'test_user_002',
    '456 Dragon Avenue, Richmond, BC V6X 2B2',
    ARRAY['V6X', 'V6Y', 'V7A'],
    ARRAY['1010000', '1010100'],
    'active',
    ARRAY['license_002.pdf', 'health_permit_002.pdf'],
    'BC-REST-002',
    203,
    'corporate',
    true,
    'BN987654321RT0001',
    150000,
    true,
    true,
    NULL,
    '{"business_license": "valid", "health_permit": "valid", "fire_safety": "certified"}',
    'verified',
    true,
    12,
    20.0,
    80.00,
    'variable',
    '{"monday": {"open": "10:30", "close": "22:30"}, "tuesday": {"open": "10:30", "close": "22:30"}, "wednesday": {"open": "10:30", "close": "22:30"}, "thursday": {"open": "10:30", "close": "22:30"}, "friday": {"open": "10:30", "close": "23:00"}, "saturday": {"open": "10:30", "close": "23:00"}, "sunday": {"open": "10:30", "close": "22:00"}}',
    '{"executive_chef": "Chef Wong", "dim_sum_chef": "Chef Liu", "wok_masters": 2, "servers": 8}',
    '{"cash": true, "credit_card": true, "debit": true, "alipay": true, "wechat_pay": true}',
    true,
    false,
    '{"email": true, "sms": false, "push": true}',
    '{"en": "Golden Dragon Restaurant", "zh": "金龙餐厅", "fr": "Restaurant Dragon d''Or"}',
    '{"en": "Authentic Chinese cuisine with traditional flavors and modern presentation", "zh": "正宗中式料理，传统风味现代呈现", "fr": "Cuisine chinoise authentique avec des saveurs traditionnelles et une présentation moderne"}',
    'https://example.com/avatars/golden_dragon.jpg',
    '+1-604-555-0002',
    'info@goldendragon.com',
    4.6,
    ARRAY['中式料理', '粤菜', '点心', '烧烤', '海鲜', '正宗', '家常菜'],
    '{"instagram": "@goldendragon_richmond", "facebook": "GoldenDragonRestaurant", "website": "https://goldendragon.ca"}',
    '{"specialty": "cantonese_dim_sum", "banquet_capacity": 200, "established": "2010"}',
    NOW(),
    NOW()
),

-- 寿司大师 - 专业寿司制作
(
    'test_provider_003',
    'test_user_003',
    '789 Sushi Lane, Burnaby, BC V5A 3C3',
    ARRAY['V5A', 'V5C', 'V5E'],
    ARRAY['1010000', '1010100'],
    'active',
    ARRAY['license_003.pdf', 'sushi_certification.pdf'],
    'BC-REST-003',
    89,
    'individual',
    false,
    NULL,
    65000,
    false,
    false,
    NULL,
    '{"business_license": "valid", "sushi_certification": "master_level"}',
    'verified',
    true,
    15,
    12.0,
    150.00,
    'premium',
    '{"tuesday": {"open": "17:00", "close": "22:00"}, "wednesday": {"open": "17:00", "close": "22:00"}, "thursday": {"open": "17:00", "close": "22:00"}, "friday": {"open": "17:00", "close": "23:00"}, "saturday": {"open": "17:00", "close": "23:00"}, "sunday": {"closed": true}, "monday": {"closed": true}}',
    '{"master_sushi_chef": "Yamamoto-san", "apprentice": "Kevin", "hostess": 1}',
    '{"cash": true, "credit_card": true, "japanese_payment": true}',
    true,
    false,
    '{"email": true, "sms": true, "push": false}',
    '{"en": "Sushi Master Yamamoto", "zh": "寿司大师山本", "fr": "Maître Sushi Yamamoto"}',
    '{"en": "Premium Japanese sushi and sashimi with fresh ingredients daily", "zh": "使用每日新鲜食材的高级日本寿司和刺身", "fr": "Sushi et sashimi japonais premium avec des ingrédients frais quotidiens"}',
    'https://example.com/avatars/sushi_master.jpg',
    '+1-604-555-0003',
    'info@sushimaster.com',
    4.9,
    ARRAY['寿司', '刺身', '手握', '职人', '新鲜', '高端', '预约制'],
    '{"instagram": "@sushimaster_burnaby", "website": "https://sushimaster.ca"}',
    '{"specialty": "omakase", "seating": "counter_only", "reservation_required": true}',
    NOW(),
    NOW()
),

-- 意式厨房 - 意大利料理
(
    'test_provider_004',
    'test_user_004',
    '321 Pasta Street, West Vancouver, BC V7T 4D4',
    ARRAY['V7T', 'V7V', 'V7W'],
    ARRAY['1010000', '1010200'],
    'active',
    ARRAY['license_004.pdf', 'wine_license.pdf'],
    'BC-REST-004',
    134,
    'corporate',
    true,
    'BN456789123RT0001',
    120000,
    true,
    true,
    NULL,
    '{"business_license": "valid", "wine_license": "valid", "organic_certification": "pending"}',
    'verified',
    true,
    10,
    25.0,
    95.00,
    'fixed_price',
    '{"monday": {"closed": true}, "tuesday": {"open": "17:00", "close": "22:00"}, "wednesday": {"open": "17:00", "close": "22:00"}, "thursday": {"open": "17:00", "close": "22:00"}, "friday": {"open": "17:00", "close": "23:00"}, "saturday": {"open": "17:00", "close": "23:00"}, "sunday": {"open": "17:00", "close": "21:00"}}',
    '{"head_chef": "Chef Marco", "pasta_chef": "Chef Sofia", "sommelier": "Antonio", "servers": 6}',
    '{"cash": true, "credit_card": true, "debit": true, "apple_pay": true}',
    true,
    false,
    '{"email": true, "sms": true, "push": true}',
    '{"en": "Bella Italia Kitchen", "zh": "贝拉意大利厨房", "fr": "Cuisine Bella Italia"}',
    '{"en": "Traditional Italian cuisine with authentic recipes from various regions of Italy", "zh": "来自意大利各地区的传统正宗食谱", "fr": "Cuisine italienne traditionnelle avec des recettes authentiques de diverses régions d''Italie"}',
    'https://example.com/avatars/bella_italia.jpg',
    '+1-604-555-0004',
    'info@bellaitalia.com',
    4.7,
    ARRAY['意大利料理', '意面', '披萨', '红酒', '正宗', '浪漫', '约会'],
    '{"instagram": "@bellaitalia_westvancouver", "facebook": "BellaItaliaKitchen", "website": "https://bellaitalia.ca"}',
    '{"specialty": "handmade_pasta", "wine_collection": "extensive", "private_dining": true}',
    NOW(),
    NOW()
),

-- 小龙虾王 - 特色海鲜
(
    'test_provider_005',
    'test_user_005',
    '567 Seafood Boulevard, Surrey, BC V3T 5E5',
    ARRAY['V3T', 'V3S', 'V3R'],
    ARRAY['1010000', '1010100'],
    'active',
    ARRAY['license_005.pdf', 'seafood_permit.pdf'],
    'BC-REST-005',
    178,
    'individual',
    true,
    'BN789123456RT0001',
    95000,
    true,
    false,
    NULL,
    '{"business_license": "valid", "seafood_permit": "valid", "halal_certification": "na"}',
    'verified',
    true,
    6,
    18.0,
    75.00,
    'seasonal',
    '{"monday": {"open": "16:00", "close": "23:00"}, "tuesday": {"open": "16:00", "close": "23:00"}, "wednesday": {"open": "16:00", "close": "23:00"}, "thursday": {"open": "16:00", "close": "00:00"}, "friday": {"open": "16:00", "close": "01:00"}, "saturday": {"open": "15:00", "close": "01:00"}, "sunday": {"open": "15:00", "close": "23:00"}}',
    '{"chef": "Chef Chen", "seafood_specialist": "Master Liu", "servers": 4, "kitchen_staff": 3}',
    '{"cash": true, "credit_card": true, "debit": true, "mobile_payment": true}',
    true,
    false,
    '{"email": true, "sms": true, "push": true}',
    '{"en": "Crawfish King", "zh": "小龙虾王", "fr": "Roi des Écrevisses"}',
    '{"en": "Specialty seafood restaurant focusing on fresh crawfish and Sichuan-style preparation", "zh": "专业海鲜餐厅，主打新鲜小龙虾和川式制作", "fr": "Restaurant de fruits de mer spécialisé dans les écrevisses fraîches et la préparation style Sichuan"}',
    'https://example.com/avatars/crawfish_king.jpg',
    '+1-604-555-0005',
    'info@crawfishking.com',
    4.5,
    ARRAY['小龙虾', '海鲜', '川菜', '麻辣', '新鲜', '夜宵', '聚餐'],
    '{"instagram": "@crawfishking_surrey", "facebook": "CrawfishKingSurrey"}',
    '{"specialty": "spicy_crawfish", "live_seafood": true, "group_dining": "specialty"}',
    NOW(),
    NOW()
)

ON CONFLICT (id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    bio = EXCLUDED.bio,
    phone = EXCLUDED.phone,
    email = EXCLUDED.email,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    updated_at = NOW();

-- 验证插入结果
DO $$
BEGIN
    RAISE NOTICE '✅ Provider测试数据插入完成！';
    RAISE NOTICE '📊 插入了5个测试Provider：樱花日料、金龙餐厅、寿司大师、贝拉意大利厨房、小龙虾王';
    RAISE NOTICE '🌐 所有Provider都包含多语言字段支持（中文、英文、法文）';
    RAISE NOTICE '📱 包含完整的联系信息、评分、认证状态等真实数据';
END $$;

-- 显示插入的数据摘要
SELECT 
    'Provider Data Summary' as summary,
    COUNT(*) as total_providers,
    COUNT(CASE WHEN status = 'active' THEN 1 END) as active_providers,
    COUNT(CASE WHEN is_certified = true THEN 1 END) as certified_providers,
    ROUND(AVG(rating), 2) as average_rating,
    SUM(review_count) as total_reviews
FROM provider_profiles 
WHERE id LIKE 'test_provider_%';

-- 显示多语言支持验证
SELECT 
    'Multilingual Support Verification' as check_type,
    id,
    display_name->>'en' as english_name,
    display_name->>'zh' as chinese_name,
    email,
    rating,
    review_count
FROM provider_profiles 
WHERE id LIKE 'test_provider_%'
ORDER BY id;
